#!/bin/zsh

export CID=$(cat ./.cid)
export AUTH="Authorization: Bearer $(cat ./.secret)"
export BASE="https://canvas.northwestern.edu/api/v1"

export ROSTER_DIR="group_rosters"
mkdir -p $ROSTER_DIR
export TEMPLATE_DIR="group_templates"
mkdir -p $TEMPLATE_DIR

groups=$(curl -s -X GET "$BASE/courses/$CID/groups" \
    -H $AUTH \
    | jq -rc '.[] | { id: .id, name: .name }')

for ginfo in ${(f)groups}; do
    gid=$(jq '.id' <<< $ginfo)
    gname=$(jq '.name' <<< $ginfo)

    echo "Making roster/template info for group $gname"

    res=$(curl -s -X GET "$BASE/groups/$gid/users" -H $AUTH)
    members=$(jq -c '.[]' <<< $res)

    roster_file="$ROSTER_DIR/${gid}_roster.csv"
    echo "$gname Team Roster" >> $roster_file
    echo "netid,canvas_id,name" >> $roster_file

    template_file="$TEMPLATE_DIR/${gid}_template.csv"
    echo "$gname Score Template" >> $template_file
    echo "netid,name,score" >> $template_file

    for mem in ${(f)members}; do
        name=$(jq -r '.name' <<< $mem)
        id=$(jq -r '.id' <<< $mem)
        info=$(curl -s -X GET "$BASE/courses/$CID/users/$id" -H $AUTH)
        netid=$(jq -r '.sis_user_id' <<< $info)

        echo "$netid,$id,$name" >> $roster_file
        echo "$netid,$name,100" >> $template_file
    done
done
